# .pre-commit-config.yaml
repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.22.0
    hooks:
      - id: commitlint
        stages: [commit-msg]
        # These are dependencies for the hook itself, which commitlint needs
        additional_dependencies: ['@commitlint/config-conventional']
        # Point to your configuration file
        args: ["--config", ".commitlint.config.js"]